# Generated by Django 3.1.7 on 2021-02-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210224_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='allergy_drink',
            field=models.ManyToManyField(blank=True, through='products.AllergyDrink', to='products.Allergy'),
        ),
        migrations.AlterField(
            model_name='allergydrink',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.allergy'),
        ),
        migrations.AlterField(
            model_name='allergydrink',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
        migrations.AlterModelTable(
            name='allergy',
            table='allergies',
        ),
        migrations.AlterModelTable(
            name='allergydrink',
            table='allergies_drinks',
        ),
    ]
